// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKXxFaK_XDGVZtzHGYiRJu9tc9my5vMqM',
    appId: '1:10069940294:web:327bd917ff51452f709247',
    messagingSenderId: '10069940294',
    projectId: 'modern-ui-flutter',
    authDomain: 'modern-ui-flutter.firebaseapp.com',
    storageBucket: 'modern-ui-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkf3zYfHTJ6EjvaoKOQznyxPqmxecotZc',
    appId: '1:10069940294:android:2ddb0240070cb6d7709247',
    messagingSenderId: '10069940294',
    projectId: 'modern-ui-flutter',
    storageBucket: 'modern-ui-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcu87gY-6qomOSVTV3Dj-ipyYIbOrlPGQ',
    appId: '1:10069940294:ios:1f1fd33c76c0752e709247',
    messagingSenderId: '10069940294',
    projectId: 'modern-ui-flutter',
    storageBucket: 'modern-ui-flutter.appspot.com',
    iosClientId: '10069940294-3trek3849qhe8749vlnjiqin85jj34mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcu87gY-6qomOSVTV3Dj-ipyYIbOrlPGQ',
    appId: '1:10069940294:ios:1f1fd33c76c0752e709247',
    messagingSenderId: '10069940294',
    projectId: 'modern-ui-flutter',
    storageBucket: 'modern-ui-flutter.appspot.com',
    iosClientId: '10069940294-3trek3849qhe8749vlnjiqin85jj34mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernLogin',
  );
}
